spring.application.name=botica

# Conexión universal sin contraseña
spring.datasource.url=jdbc:mysql://localhost:3306/db_botica?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Migración automática de clases a tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=9095

# Sincronización de base de datos